export interface User {
    id: number,
    surname: string,
    name: string,
    patronymic: string,
    birthDate: Date,
    gender: string,
    passportSerial: string,
    passportNumber: string,
    authority: string,
    issueDate: Date,
    idNumber: string,
    birthplace: string,
    city: string,
    address: string,
    homePhone: string,
    handPhone: string,
    email: string,
    familyStatus: string,
    citizenship: string,
    disability: string,
    pensioner: boolean,
    income: string,
    reservist: boolean
}