export interface User {
    id: number,
    surname: string,
    name: string,
    fatherName: string,
    dateOfBirth: Date,
    gender: string,
    passportSerial: string,
    passportNumber: string,
    issuedBy: string,
    issuedDate: Date,
    identifyNumber: string,
    cityOfResidence: string,
    addressOfResidence: string,
    homePhone: string,
    cellPhone: string,
    email: string,
    placeOfWork: string,
    position: string,
    livingCity: string,
    livingAddress: string,
    familyPosition: string,
    citizen: string,
    invalidity: string,
    retired: boolean,
    monthlyIncome: number,
    military: boolean
}